"""Add columns to event model

Revision ID: d995b26ad946
Revises: 9cb93769503d
Create Date: 2022-03-26 16:36:14.433977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd995b26ad946'
down_revision = '9cb93769503d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_type', sa.String(length=64), nullable=True))
    op.add_column('events', sa.Column('organizer', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_organizer'), 'events', ['organizer'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_organizer'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_column('events', 'organizer')
    op.drop_column('events', 'event_type')
    # ### end Alembic commands ###
